# Basic Information 
title: Mateusz Jurewicz
position: Senior ML/AI Engineer
scientific_title: PhD in Computer Science
affiliation: IT University of Copenhagen
affiliation_link: https://en.itu.dk/Research/Departments/Computer-Science-Department
# affiliation_logo: ./assets/img/university-logo-small-horizontal-white-156eae9527.svg
email: mateusz.jurewicz@gmail.com

# Search Engine Optimization (SEO)
keywords: mateusz jurewicz, mateusz, jurewicz, machine learning, artificial intelligence, phd, academic, cv, online cv
canonical: https://mateuszjurewicz.github.io/
description: Mateusz Jurewicz holds a PhD in Computer Science from the IT University of Copenhagen. He is an experienced ML/AI researcher and software engineer focused on AI Safety. 

# The option is used to enable the Johns Hopkins template.
enable_hopkins_logo: false

# The option is used to show the last update time.
enable_last_update: false

# Links
link_type: icon #text/icon
google_scholar: https://scholar.google.dk/citations?user=VYr8R8wAAAAJ
cv_link: https://drive.google.com/file/d/1HAfiZShizOecs12jf8x-v5KC70Rvu5Du/view?usp=sharing
github_link: https://github.com/mateuszjurewicz
linkedin: https://www.linkedin.com/in/mateusz-jurewicz-phd-a084aa6a/
twitter: https://twitter.com/MateuszJurewic1

# Images 
avatar: ./assets/img/avatar.png
# avatar: https://i.ibb.co/KFWpcv4/Mateusz-3-modified.png
# favicon: ./assets/img/favicon.png
# favicon_dark: ./assets/img/favicon-dark.png

# # Footnotes
# footnote: Feel free to use my website's source code.
# footnote_link: https://github.com/yaoyao-liu/minimal-light

# Analytics
# Please remove the following lines about analytics services if you fork my project. 
# Otherwise, the analytics information of your website will be recorded to my ClustrMaps accounts.
# clustrmaps_id: CJD8XwsJhSyQ6sbsU-Gw0cNcUlbah7KW3xvHN2QlwW0

# The following files will be removed from the generated website.
exclude:
  - build.sh
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - CNAME
